# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: opentok_test_development
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: opentok_test_testing
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: opentok_test_production
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432